apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: car-keeper
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nomankhokhar/Car-Keeper-AutoZone-Hub.git        # ✔ your repo
    targetRevision: main                                                        # ✔ branch name
    path: kubernetes-deployment/app-with-argocd-deployement                     # ✔ folder containing k8s yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
