version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=caruser
      - DB_PASSWORD=carpassword
      - DB_NAME=car
    depends_on:
        db:
          condition: service_healthy

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=caruser
      - POSTGRES_PASSWORD=carpassword
      - POSTGRES_DB=car
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caruser -d car"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: